### ISSUE TITLE
Update information in giswiki

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx#218]
Estimated duration: ~0.25d
- [x] Add target="_blank" to **all** links
- [x] Remove link to mockup
- [x] Update function of the team members or remove this part
- [x] Remove link to Raphaels profile because there are no information
- [x] Remove the link to Eugenes activities schedule. &rarr; Should this schedule really be public?
- [ ] Rename map gallery. The relation to the osmaxx project is not clear.
- [x] "Some explanations (incomplete):" &rarr; Shouldn't this be a title?
- [x] "Data Model:" &rarr; Shouldn't this be a title?
- [x] Remove the data model by a reference to the document containing this information

**Comment by sfkeller** [comment]
Done except the map gallery which is an important part of the project!

Remind that this wiki page is currently a placeholder. It will be replaced by the web app. It then converts to a pointer to the web app and with archive info.

**Comment by wasabideveloper** [comment]
@sfkeller Please don't close issues by yourself. We always send issues to someone for review by adding the following comment:

To be review by:
- [ ] @wasabideveloper
- [ ] @njordan-hsr 
- [ ] @das-g 

Then the reviewers will add comments and after all comments have been discused and fixed if necessary, someone of the reviewers will close the issue.

**Comment by wasabideveloper** [comment]
- [ ] `target _blank` on external links seems not to work
- [ ] Functions of the team member are still wrong
  **Proposal**:
  ```
  Project staff (mainly from Geometa Lab HSR):

    Stefan: Lead and concept
    Raphael: Coordination, integration, web application, GIS conversion backend
    Tobias: Coordination, integration, web application
    Nicola: Coordination, integration, web application, GIS conversion backend
    Dhruv: PostGIS loading and schema transformation/data homogenization
    Van An: QGIS symbology 

 Former staff members:

    Eugene: PostGIS loading and schema transformation/data homogenization
    Lukas: Extraction tool chain (Linux tools, ...)
    Martin: ArcGIS symbology (ArcGIS) 
  ```
- [ ] Rename the map gallery to what it is, e.g. "Excerpt examples visualized by QGIS")
- [ ] This shouldn't really be a title?
  - "Some explanations (incomplete):"
  - "Data Model:"

**Comment by wasabideveloper** [comment]
@sfkeller What's the status of this improvements?

**Comment by sfkeller** [comment]
I'll fix that a.s.a.p.

**Comment by hixi** [comment]
@sfkeller is this fixed and can we therefor close this issue?
